// -------------------------------------------------------
// FINALIDADE: Exercício Acadêmico / Estudo de Lógica
// DESCRIÇÃO: Algoritmo para cálculo de área de triângulo.
// OBSERVAÇÃO: Este código é um pseudocódigo didático.
// -------------------------------------------------------
Algoritmo_area_triangulo
Declare base,altura,area: Real;
Escreva ("informe o valor da base do triangulo:");
Leia(base);
Escreva ("informe o valor da altura do triângulo:");
Leia(altura); 
area <- (base*altura)/2
Escreva("A area do triângulo é:", area)
Fimalgoritmo
